aws_region      = "us-west-1"
environment     = "dev"
app_name        = "myapp"
vpc_id          = "vpc-0603547ccdb32abab"
subnet_id       = "subnet-015c89b189a7d00a4"
ecs_instance_type = "t3.medium"
s3_bucket_name  = "myappprodbucketharsh"
